apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" .Release.Name "terriamap-config-server" | trunc 63 | trimSuffix "-" | quote }}
  labels:
    {{- include "terria.labels" . | nindent 4 }}
data:
  serverconfig.json: {{ toJson .Values.serverConfig | indent 2 | quote }}