apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "thredds.fullname" . }}
  labels:
    {{- include "thredds.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "thredds.selectorLabels" . | nindent 6 }}
  serviceName: "thredds"
  volumeClaimTemplates:
          - metadata:
             name: {{ .Values.pvc.configuration.name }}
            spec:
              storageClassName: {{ .Values.pvc.configuration.storageClassName | quote }}
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
          - metadata: 
              name: {{ .Values.pvc.netcdfMontlyYearly.name }}
            spec:
              storageClassName: {{ .Values.pvc.netcdfMontlyYearly.storageClassName | quote }}
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 200Gi
          - metadata: 
              name: {{ .Values.pvc.netcdfDaily1.name }}
            spec:
              storageClassName: {{ .Values.pvc.netcdfDaily1.storageClassName | quote }}
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 200Gi
          - metadata: 
              name: {{ .Values.pvc.netcdfDaily2.name }}
            spec:
              storageClassName: {{ .Values.pvc.netcdfDaily2.storageClassName | quote }}
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 200Gi
          - metadata: 
              name: {{ .Values.pvc.netcdfDaily3.name }}
            spec:
              storageClassName: {{ .Values.pvc.netcdfDaily2.storageClassName | quote }}
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 200Gi
          - metadata:
              name: {{ .Values.pvc.era5LandData.name }}
            spec:
              storageClassName: {{ .Values.pvc.era5LandData.storageClassName | quote }}
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 200Gi
          - metadata:
              name: {{ .Values.pvc.trmmData.name }}
            spec:
              storageClassName: {{ .Values.pvc.trmmData.storageClassName | quote }}
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
          - metadata:
              name: {{ .Values.pvc.ncepData.name }}
            spec:
              storageClassName: {{ .Values.pvc.ncepData.storageClassName | quote }}
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
          - metadata:
              name: {{ .Values.pvc.gpcpData.name }}
            spec:
              storageClassName: {{ .Values.pvc.gpcpData.storageClassName | quote }}
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "thredds.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "thredds.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init-{{ .Chart.Name }}
        image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
        imagePullPolicy: {{ .Values.initImage.pullPolicy }}
        volumeMounts:
        - name: {{ .Values.pvc.configuration.name }}
          mountPath: "/thredds-content"
        command: ["cp", "-r", "thredds", "thredds-content"]
      containers:
        - name: {{ .Chart.Name }}-sidecar
          image: "{{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag }}"
          imagePullPolicy: {{ .Values.sidecar.image.pullPolicy }}
          command: ["tail", "-f", "/dev/null"]
          volumeMounts:
          - mountPath: "/usr/local/monthly-yearly-data"
            name:  {{ .Values.pvc.netcdfMontlyYearly.name }}
          - mountPath: "/usr/local/daily-1-data"
            name:  {{ .Values.pvc.netcdfDaily1.name }}
          - mountPath: "/usr/local/daily-2-data"
            name:  {{ .Values.pvc.netcdfDaily2.name }}
          - mountPath: "/usr/local/daily-3-data"
            name:  {{ .Values.pvc.netcdfDaily3.name }}
          - mountPath: "/usr/local/era5-land"
            name:  {{ .Values.pvc.era5LandData.name }}
          - mountPath: "/usr/local/trmm"
            name:  {{ .Values.pvc.trmmData.name }}
          - mountPath: "/usr/local/ncep"
            name:  {{ .Values.pvc.ncepData.name }}
          - mountPath: "/usr/local/gpcp"
            name:  {{ .Values.pvc.gpcpData.name }}
          env:
          - name: CONCURRENT_REQUESTS
            value: {{ .Values.sidecar.awsConcurrentRequests | quote }}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "thredds.fullname" . }}
                key: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "thredds.fullname" . }}
                key: aws-secret-access-key
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: "/usr/local/tomcat/content"
            name:  {{ .Values.pvc.configuration.name }}
          - mountPath: "/usr/local/monthly-yearly-data"
            name:  {{ .Values.pvc.netcdfMontlyYearly.name }}
          - mountPath: "/usr/local/daily-1-data"
            name:  {{ .Values.pvc.netcdfDaily1.name }}
          - mountPath: "/usr/local/daily-2-data"
            name:  {{ .Values.pvc.netcdfDaily2.name }}
          - mountPath: "/usr/local/daily-3-data"
            name:  {{ .Values.pvc.netcdfDaily3.name }}
          - mountPath: "/usr/local/era5-land"
            name:  {{ .Values.pvc.era5LandData.name }}
          - mountPath: "/usr/local/trmm"
            name:  {{ .Values.pvc.trmmData.name }}
          - mountPath: "/usr/local/ncep"
            name:  {{ .Values.pvc.ncepData.name }}
          - mountPath: "/usr/local/gpcp"
            name:  {{ .Values.pvc.gpcpData.name }}
          ports:
            - name: liveness-port
              containerPort: {{ .Values.service.port }}
              hostPort: {{ .Values.service.port }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /thredds/catalog.html
              port: liveness-port
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /thredds/catalog.html
              port: liveness-port
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
