apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thredds.fullname" . }}
  labels:
      {{- include "thredds.labels" . | nindent 4 }}
type: Opaque
data:
  aws-access-key-id: {{ .Values.awsAccessKeyId | b64enc }}
  aws-secret-access-key: {{ .Values.awsSecretAccessKey | b64enc }}